'use strict';
const assert=require('node:assert/strict');
require('./static/review-labels.js');
const labels=globalThis.ReviewLabels;
assert.equal(labels.groups.find(group=>group.id==='topic').items.length,0,'Project topics are supplied by the catalog');
labels.configureTopics([{id:'spectral_sequence',name:'谱序列'},{id:'adams',name:'Adams 理论'},{id:'sphere',name:'球谱'}]);
const model={declaration:'KIP126.Classical.Adams.sphereAdamsData',module_file:'KIP126/Interface/Axiom/StandardSphere/Sequence/Data.lean',kind:'abbrev',priority:95,risk:'high',verdict:'aligned'};
const tags=labels.forCard(model);
assert(tags.includes('role/definition'));
assert(tags.includes('topic/adams'));
assert(!tags.some(id=>id.startsWith('risk/')),'Risk is not a separate frontend label dimension');
assert(tags.includes('status/aligned'));
assert(labels.matches(tags,new Set(['role/definition','role/input'])),'Selections in one dimension are OR');
assert(labels.matches(tags,new Set(['role/definition','topic/adams'])),'Selections across dimensions are AND');
assert(!labels.matches(tags,new Set(['role/input','topic/adams'])));
assert(labels.matches(tags,new Set(['role/input','topic/adams']),'role'),'Facet counts ignore only their own dimension');
assert(!labels.matches(tags,new Set(['role/definition','topic/spectral_sequence']),'role'));
assert(labels.matches(tags,new Set()),'Clearing filters restores all records');
assert(labels.forCard({...model,stale:true}).includes('status/pending'));
assert(labels.forCard({...model,verdict:null}).includes('status/pending'),'New and outdated judgments share the pending queue');
assert(!labels.forCard({...model,stale:true}).includes('status/aligned'));
assert(labels.forCard({...model,statement_origin:'backtranslation'}).includes('readback/draft'));
assert(labels.forCard({...model,module_file:'KIP126/Main/Axiom/Literature/Example.lean',kind:'axiom'}).includes('role/input'),'Legacy literature records use the consolidated input role');
assert(!labels.groups.some(group=>group.id==='risk'));
for(const id of ['role/model','role/literature','role/computed','role/transport','role/challenge','role/unclassified','topic/comparison','topic/spectral','status/stale','topic/certificate','readback/context','risk/unknown'])assert(!labels.definitions.has(id),'Removed labels are not offered');
const migrated=labels.normalizeSelection(['status/stale','status/pending','topic/certificate','role/computed','readback/context','risk/unknown','topic/spectral','topic/comparison','role/transport','removed/unknown']);
assert.deepEqual([...migrated],['status/pending','role/computation','readback/draft','topic/spectral_sequence','role/comparison'],'Old links migrate to the new dimensions and deduplicate');
const selection=new Set(['role/definition','topic/adams','status/pending']);
assert.equal(labels.reviewBucket(selection),'pending');
labels.setReviewScope(selection,'reviewed');
assert.equal(labels.reviewBucket(selection),'reviewed');
assert(labels.matches(tags,selection));
assert(!labels.matches(labels.forCard({...model,stale:true}),selection),'Old passes cannot enter the reviewed queue');
assert(labels.matches(labels.forCard({...model,stale:true}),selection,'status'),'Status facet counts are independent of the sidebar status');
assert(selection.has('role/definition')&&selection.has('topic/adams'),'Status shortcuts preserve other dimensions');
labels.setReviewScope(selection,'pending');
assert.equal(labels.reviewBucket(selection),'pending');
assert(!labels.matches(tags,selection));
assert(labels.matches(labels.forCard({...model,stale:true}),selection));
selection.add('status/uncertain');
assert.equal(labels.reviewBucket(selection),null,'Mixed subsets do not misleadingly highlight All');
labels.setReviewScope(selection,'all');
assert.deepEqual([...selection],['role/definition','topic/adams']);
assert.equal(labels.reviewBucket(selection),'all');
assert.equal(labels.reviewBucket(new Set(['status/misaligned'])),'reviewed');
assert.equal(labels.reviewState({...model,verdict:'partial'}),'uncertain');
const imported=labels.forCard({...model,enrichment:{classification:{role:'literature',topics:['sphere']},priority:{level:null}}});
assert(imported.includes('role/input')&&!imported.includes('role/definition'),'Imported classification takes precedence over directory heuristics');
assert(imported.includes('topic/sphere')&&!imported.includes('topic/adams'),'Explicit imported topics replace heuristic topics');
assert(!imported.some(id=>id.startsWith('priority/')),'An unassigned priority cannot be silently downgraded to P2');
assert(labels.forCard({...model,enrichment:{priority:{level:'p0'}}}).includes('priority/p0'));
assert(!labels.forCard({...model,enrichment:{classification:{role:'unclassified',topics:['comparison','spectral']},priority:{level:null}}}).some(id=>id.startsWith('role/')),'Unknown legacy roles remain unclassified');
assert(labels.forCard({...model,enrichment:{classification:{role:'unclassified',topics:['comparison','spectral']},priority:{level:null}}}).includes('topic/spectral_sequence'));
const v2={...model,main_target:true,enrichment:{schema:'statement-enrichment.v2',readback:{status:'draft',text_zh:'草稿'},classification:{role:null,topics:[]},priority:null}};
const unclassified=labels.forCard(v2);
assert(!unclassified.some(id=>/^(role|topic|priority)\//.test(id)),'Explicit v2 unknowns never inherit directory roles, heuristic topics or priority');
assert(unclassified.includes('readback/draft')&&unclassified.includes('status/aligned'),'Machine drafts do not replace personal review status');
assert(labels.forCard({...v2,enrichment:{...v2.enrichment,classification:{role:'derivation',topics:['adams','unregistered']},priority:'p1'}}).includes('priority/p1'));
assert(!labels.forCard({...v2,enrichment:{...v2.enrichment,classification:{role:'derivation',topics:['unregistered']}}}).includes('topic/unregistered'),'Only configured topics can become filter labels');
labels.configureTopics([{id:'topology',name:'拓扑学'},{id:'geometry',name:'几何学'}]);
assert(!labels.definitions.has('topic/adams'),'Switching projects removes the previous topic collection');
assert.deepEqual([...labels.normalizeSelection(['topic/topology','topic/adams'])],['topic/topology']);
const topology=labels.forCard({...v2,enrichment:{...v2.enrichment,classification:{role:'derivation',topics:['topology','topology','geometry']}}});
assert(topology.includes('topic/topology')&&topology.includes('topic/geometry'),'New project topics work without frontend code changes');
assert.equal(topology.filter(id=>id==='topic/topology').length,1);
assert(labels.matches(topology,new Set(['role/derivation','topic/topology'])));
assert.equal(labels.definitions.get('topic/topology').name,'拓扑学');
assert.throws(()=>labels.configureTopics([{id:'duplicate',name:'一'},{id:'duplicate',name:'二'}]),/重复/);
assert(labels.definitions.has('topic/topology'),'Invalid configuration does not clear the current project');
labels.configureTopics([]);
assert(!labels.forCard(v2).some(id=>id.startsWith('topic/')),'An empty project topic collection is valid');
console.log('Label filtering, project topic configuration, v1 migration, v2 unknowns and personal review states passed');
