'use strict';
const assert=require('node:assert/strict');
require('./static/review-labels.js');
const labels=globalThis.ReviewLabels;
const model={declaration:'KIP126.Classical.Adams.sphereAdamsData',module_file:'KIP126/Interface/Axiom/StandardSphere/Sequence/Data.lean',kind:'abbrev',priority:95,risk:'high',verdict:'aligned'};
const tags=labels.forCard(model);
assert(tags.includes('role/model'));
assert(tags.includes('topic/adams'));
assert(!tags.some(id=>id.startsWith('risk/')),'Risk is not a separate frontend label dimension');
assert(tags.includes('status/aligned'));
assert(labels.matches(tags,new Set(['role/model','role/literature'])),'Selections in one dimension are OR');
assert(labels.matches(tags,new Set(['role/model','topic/adams'])),'Selections across dimensions are AND');
assert(!labels.matches(tags,new Set(['role/literature','topic/adams'])));
assert(labels.matches(tags,new Set(['role/literature','topic/adams']),'role'),'Facet counts ignore only their own dimension');
assert(!labels.matches(tags,new Set(['role/model','topic/spectral']),'role'));
assert(labels.matches(tags,new Set()),'Clearing filters restores all records');
assert(labels.forCard({...model,stale:true}).includes('status/pending'));
assert(labels.forCard({...model,verdict:null}).includes('status/pending'),'New and outdated judgments share the pending queue');
assert(!labels.forCard({...model,stale:true}).includes('status/aligned'));
assert(labels.forCard({...model,statement_origin:'backtranslation'}).includes('readback/draft'));
assert(labels.forCard({...model,module_file:'KIP126/Main/Axiom/Literature/Example.lean',kind:'axiom'}).includes('role/literature'),'Axiom kind does not hide literature provenance');
assert.equal(new Set([...labels.definitions.keys()]).size,23);
assert(!labels.groups.some(group=>group.id==='risk'));
for(const id of ['status/stale','topic/certificate','readback/context','risk/unknown','risk/no-findings','risk/suspected','risk/confirmed'])assert(!labels.definitions.has(id),'Removed labels are not offered');
const migrated=labels.normalizeSelection(['status/stale','status/pending','topic/certificate','role/computed','readback/context','risk/unknown','removed/unknown']);
assert.deepEqual([...migrated],['status/pending','role/computed','readback/draft'],'Old links migrate and deduplicate instead of dropping their filters');
const selection=new Set(['role/model','topic/adams','status/pending']);
assert.equal(labels.reviewBucket(selection),'pending');
labels.setReviewScope(selection,'reviewed');
assert.equal(labels.reviewBucket(selection),'reviewed');
assert(labels.matches(tags,selection));
assert(!labels.matches(labels.forCard({...model,stale:true}),selection),'Old passes cannot enter the reviewed queue');
assert(labels.matches(labels.forCard({...model,stale:true}),selection,'status'),'Status facet counts are independent of the sidebar status');
assert(selection.has('role/model')&&selection.has('topic/adams'),'Status shortcuts preserve other dimensions');
labels.setReviewScope(selection,'pending');
assert.equal(labels.reviewBucket(selection),'pending');
assert(!labels.matches(tags,selection));
assert(labels.matches(labels.forCard({...model,stale:true}),selection));
selection.add('status/uncertain');
assert.equal(labels.reviewBucket(selection),null,'Mixed subsets do not misleadingly highlight All');
labels.setReviewScope(selection,'all');
assert.deepEqual([...selection],['role/model','topic/adams']);
assert.equal(labels.reviewBucket(selection),'all');
assert.equal(labels.reviewBucket(new Set(['status/misaligned'])),'reviewed');
assert.equal(labels.reviewState({...model,verdict:'partial'}),'uncertain');
const imported=labels.forCard({...model,enrichment:{classification:{role:'literature',topics:['sphere']},priority:{level:null}}});
assert(imported.includes('role/literature')&&!imported.includes('role/model'),'Imported classification takes precedence over directory heuristics');
assert(imported.includes('topic/sphere')&&!imported.includes('topic/adams'),'Explicit imported topics replace heuristic topics');
assert(!imported.some(id=>id.startsWith('priority/')),'An unassigned priority cannot be silently downgraded to P2');
assert(labels.forCard({...model,enrichment:{priority:{level:'p0'}}}).includes('priority/p0'));
console.log('Label composition, unified review queue, link migration, facet counts and evidence boundaries passed');
